# Name of the dictionary file used to source words definitions
# The dictionary file must follow the JIJI format => https://github.com/juliango202/jiji
dictionary: jmdict_english.jiji.yaml

# Font-size to use when writing dictionary definitions
# A low resolution video will need a higher font-size, and vice-versa
definitionSize: 9

# List of colors to use successively to highlight the defined words in a subtitle caption.
# For beginners it helps to highlight words in different colors to make parsing easier
# and to find the correponding definition more quickly. In that case use you can use:
#- '#FFAAAA'
#- '#AAAAFF'
#- '#AAFFAA'
#- '#FFAAFF'
#- '#AAFFFF'
# For more advanced users it's probably better to not highlight words and use
# only white text(this is the default)
highlightColors:
- '#FFFFFF'

# The list of PartOfSpeech to annotate
# The subtitle words with a detected PartOfSpeech NOT in this list will be ignored
# See http://universaldependencies.org/u/pos/all.html for the possible values
# The default is to display definitions for NOUN, VERB, ADJ, and ADV
partOfSpeechToAnnotate:
- NOUN
- VERB
- ADJ
- ADV

# Flag to display all lemmas of a defined word or not.
# When a dictionary definition is associated with several lemmas(e.g. アップデート, アップデイト),
# you can set this option to true to display them all
# otherwise set to false(default) to display only the lemma that appears in the caption
displayOtherLemma: false

# Ignore words if they have a specific tag in the dictionary
# Entries in a jiji dictionary can be tagged, for example the tags freq01 to freq12 can be
# used to represent the frequency of the entry
# If you expect to already understand frequent words, you can put freq01, freq02, ... in the list below
# and the definition for those words won't be displayed
# NOTE: be conservative because frequency information is often missing and not always reliable
# Currently Japanese language tags are: freq01->freq12, jlpt1->jlpt5, and nfXX tags copied from JMdict
ignoreTags:
- freq01
- freq02

# Ignore words in the list below
# You can put here the list of words that you don't want defined because you already know them
ignoreWords:
- あ
- ああ